sprint2/step2
zhukovk4010/react-burger pull request #4
Opened 2023-02-26 13:37 UTC by zhukovk4010

2023-02-26 14:27 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику, переделать div в ссылки.

- У вас возникает ошибка в консоли, если перетащить только ингредиент: <https://disk.yandex.com/i/Jh69-G0hzikLww>;

- Нужно запретить нажатие кнопки, если пользователь выбрал только ингредиенты <https://disk.yandex.com/i/aM2KTpEZ3mv4ww>;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/FZ0eomTE_1BXyQ>;

- Иконка <https://disk.yandex.com/i/vbPrv1tIWY2JRg> не совпадает с той, что в макете;

- Не нужно создавать каждый экшен в отдельном файле. У вас есть определенная область, которая относится к экшену, нужно создать 1 файл и перенести в него все экшены. Например для области ingredients, нужно просто создать файл `service/actions/ingredients.js` и писать все экшены там;

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу;

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/thunk/getIngredientsThunk.js
> +            const res = await fetch(URL_INGREDIENTS);
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше  разместить их в отдельном файле  `utils/burger-api.js`

Например:

```js

const NORMA_API = `https://norma.nomoreparties.space/api`;

export function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(checkResponse )
}

export function sendOrder(data) {
   return fetch(`${NORMA_API}/orders`)
    .then(checkResponse )
}

```

, а не описывать запросы в самом компоненте

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/thunk/getIngredientsThunk.js
> +                dispatch(getIngredientsSuccessAC(data.data));
**Можно лучше:**

```js
const {data} = await res.json();
dispatch(getIngredientsSuccessAC(data));
```

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/reducers/activeTabReducer.js
> +const activeTabReducer = (state = initialState, action) => {
**Надо исправить:**

Не следует отслеживать табы в редаксе, они используются только в 1 месте в приложении, поэтому хранение тут излишне.

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/reducers/ingredientsReducer.js
> +    ingredientsData: null,
**Надо исправить:**

`null` - можно ставить, если у вас пустой объект, а если у вас массив, то нужно ставить пустой массив, чтобы было понятно что в будущем там будет именно массив, а не объект.

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/reducers/modalReducer.js
> +            }
**Надо исправить:**

Лучше разделить экшен на 2 отдельных.

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/reducers/ordersReducer.js
> +    ordersData: [],
**Надо исправить:**

Здесь должно быть `null` значение, а не пустой массив.

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/reducers/ordersReducer.js
> +                ordersData: [],
**Надо исправить:**

Не забудьте и тут поправить)

2023-02-26 14:27 UTC, ArslanDev666 commented on src/services/reducers/selectedIngredientsReducer.js
> +    totalPrice: 0,
**Надо исправить:**

Цена используется только в `burger-constructor`, её лучше считать там, используя `useMemo`.

2023-02-26 14:27 UTC, ArslanDev666 commented on src/components/main/burger-constructor/BurgrerConstructor.jsx
> +                            text={selectedIngredients.selectedBun.name}
**Надо исправить:**

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2023-02-26 14:27 UTC, ArslanDev666 commented on src/components/main/burger-constructor/BurgrerConstructor.jsx
> +                dispatch(addSelectedIngredient(element, uuid()))
**Можно лучше:**

Генерировать uuid лучше в самом экшене, а не тут. Т.к. может быть ещё несколько способов добавления ингредиента в конструктор, и вам каждый раз придётся дублировать код. Поэтому лучше написать в экшене эту логику.

2023-02-26 19:06 UTC, zhukovk4010 commented
Исправил замечания
Спасибо за советы по улучшению кода, буду внедрять по ходу следующего спринта)

2023-02-27 14:20 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Рекомендую исправить:**

- В компоненте App-header требуется поправить семантику, переделать div в ссылки.

2023-03-01 19:01 UTC, merged